language: node_js

node_js:
  - '12'

services:
  - docker

install:
  - npm ci

before_script:
  - npm run dev &

script:
<<<<<<< HEAD
  - npm run test
=======
  - npm run test
>>>>>>> 45ae829 (Add or update package-lock.json file)
